require: 
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'lib/*'
    - 'db/**/*'
    - 'vendor/**/*'
  
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'config/**/*'
    - 'test/**/*'
    - 'Guardfile'

Metrics/MethodLength:
  Max: 20

Style/MultilineBlockChain:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'
    - 'config/application.rb'
    - 'app/channels/application_cable/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false
