name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bin/rails db:test:prepare
        bundle exec rubocop
        bundle exec rake
    container:
      image: ruby:2.6.5
